/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hrz_logan_TestJni */

#ifndef _Included_com_hrz_logan_TestJni
#define _Included_com_hrz_logan_TestJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hrz_logan_TestJni
 * Method:    init
 * Signature: (Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_hrz_logan_TestJni_init
  (JNIEnv *, jobject, jstring, jstring, jint, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
